FROM bitnami/spark:3.5.3

USER root

RUN apt-get update && \
apt-get install -y curl && \
apt-get clean && \
curl -o /opt/bitnami/spark/jars/hadoop-azure-3.4.1.jar \
    https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-azure/3.3.6/hadoop-azure-3.4.1.jar && \
curl -o /opt/bitnami/spark/jars/azure-storage-blob-12.29.0.jar \
    https://repo1.maven.org/maven2/com/microsoft/azure/azure-storage-blob/12.29.0/azure-storage-blob-12.29.0.jar

USER 1001
